@startuml
class com.example.progsp6.Model.Document {
- IntegerProperty id
- StringProperty name
- IntegerProperty numberOfDoc
- StringProperty category
- StringProperty type
- StringProperty status
- ObjectProperty<LocalDate> date
+ String getName()
+ StringProperty nameProperty()
+ void setName(String)
+ int getNumberOfDoc()
+ IntegerProperty numberOfDocProperty()
+ void setNumberOfDoc(int)
+ String getCategory()
+ StringProperty categoryProperty()
+ void setCategory(String)
+ String getType()
+ StringProperty typeProperty()
+ void setType(String)
+ String getStatus()
+ StringProperty statusProperty()
+ void setStatus(String)
+ LocalDate getDate()
+ ObjectProperty<LocalDate> dateProperty()
+ void setDate(LocalDate)
+ int getId()
+ IntegerProperty idProperty()
+ void setId(int)
}
class com.example.progsp6.Model.Request {
- String request
- ArrayList<Document> documents
+ String getRequest()
+ void setRequest(String)
+ ArrayList<Document> getDocuments()
+ void setDocuments(ArrayList<Document>)
}
class com.example.progsp6.Controller.MainController {
- ResourceBundle resources
- URL location
- Button addButton
- AnchorPane anchorPane
- AnchorPane anchorPane1
- AnchorPane anchorPane2
- ButtonBar buttonBar
- Label categoryLabel
- Button changeButton
- TableColumn<Document,String> columnName
- TableColumn<Document,Integer> columnNumber
- Label dateLabel
- Button deleteButton
- GridPane gridPane
- Label labelInfo
- Label nameLabel
- Label numberLabel
- SplitPane splitPane
- Label statusLabel
- TableView<Document> tableView
- Label typeLabel
- Main main
- Client client
~ Request request
~ ArrayList<Document> documentsArray
~ ObservableList<Document> documents
~ void initialize()
+ void buildTable()
+ void updateTable()
- void showDocDetails(Document)
~ void deleteDocument(ActionEvent)
- void addDocument()
- void editDocument()
}
class com.example.progsp6.Client {
+ ArrayList<Document> getData(Request)
+ ArrayList<Document> getDoc(Answer)
}
class com.example.progsp6.Main {
- Stage primaryStage
- BorderPane rootLayout
+ void start(Stage)
- void initRootLayout()
+ void showDocumentOverview()
+ boolean showDocEditDialog(Document)
+ boolean showDocAddDialog(Document)
+ {static} void main(String[])
}
class com.example.progsp6.Model.DateUtil {
- {static} String DATE_PATTERN
- {static} DateTimeFormatter DATE_FORMATTER
+ {static} String format(LocalDate)
+ {static} LocalDate parse(String)
+ {static} boolean validDate(String)
}
class com.example.progsp6.Controller.EditController {
- ResourceBundle resources
- URL location
- TextField category
- TextField date
- Button editButton
- Button exitButton
- TextField name
- TextField number
- TextField status
- TextField type
- Stage dialogStage
- Document document
- boolean okClicked
~ void initialize()
- boolean isInputValid()
+ void setDialogStage(Stage)
+ void setDoc(Document)
+ void addDoc(Document)
+ boolean isOkClicked()
- void ok()
- void cancel()
}
class com.example.progsp6.Model.Answer {
- String answer
- ArrayList<Document> documents
+ String getAnswer()
+ void setAnswer(String)
+ ArrayList<Document> getDocuments()
+ void setDocuments(ArrayList<Document>)
}


javafx.application.Application <|-- com.example.progsp6.Main
@enduml